<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="QTLSYS0-237" name="tests.QCStore" tests="16" failures="0" timestamp="10 Sep 2020 14:01:13 GMT" time="14378.099" errors="3">
  <testcase name="JQC_ILP_Deposit_Return_OtherPayment_Txn" time="657.766" classname="tests.QCStore"/>
  <testcase name="JQC_LOC_SignatureLoan_Run2Statements_WaiveFee_Txn" time="762.853" classname="tests.QCStore"/>
  <testcase name="JQC_LOC_SignatureLoan_Run2Statements_PartialWaiveFee_Txn" time="681.097" classname="tests.QCStore"/>
  <testcase name="JQC_LOC_SignatureLoan_Run2Statements_Default_PartialWaiveFee_Txn" time="804.719" classname="tests.QCStore"/>
  <testcase name="JQC_LOC_SignatureLoan_Run2Statements_Default_WaiveFee_Txn" time="757.282" classname="tests.QCStore"/>
  <testcase name="JQC_TLP_DCDeposit_Decline_2ndDeposit_Decline_Default_Repo_Redeposit_Decline_Txn" time="975.205" classname="tests.QCStore">
    <error type="java.lang.NullPointerException" message="null value in entry: url=null">
      <![CDATA[java.lang.NullPointerException: null value in entry: url=null
at com.google.common.collect.CollectPreconditions.checkEntryNotNull(CollectPreconditions.java:32)
at com.google.common.collect.SingletonImmutableBiMap.<init>(SingletonImmutableBiMap.java:42)
at com.google.common.collect.ImmutableBiMap.of(ImmutableBiMap.java:72)
at com.google.common.collect.ImmutableMap.of(ImmutableMap.java:124)
at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:276)
at tests.RepoReqDenied.repoProcess(RepoReqDenied.java:93)
at tests.QCStore.JQC_TLP_DCDeposit_Decline_2ndDeposit_Decline_Default_Repo_Redeposit_Decline_Txn(QCStore.java:512)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- JQC_TLP_DCDeposit_Decline_2ndDeposit_Decline_Default_Repo_Redeposit_Decline_Txn -->
  <testcase name="JQC_TXMPDL_Newloan_Lessthan_CSOFee_Gracedays_Payment_Txn" time="702.055" classname="tests.QCStore"/>
  <testcase name="JQC_TXMPDL_Newloan_Lessthan_CSOFee_Duedate_Payment_Txn" time="525.763" classname="tests.QCStore"/>
  <testcase name="JQC_TXMPDL_Newloan_Greaterthan_CSOFee_Gracedays_Payment_Txn" time="658.274" classname="tests.QCStore"/>
  <testcase name="JQC_TXMPDL_Newloan_Greaterthan_CSOFee_Duedate_1stInstPayment_Gracedays_2ndInstalPayment_Txn" time="764.323" classname="tests.QCStore"/>
  <testcase name="JQC_TXMPDLACH_Newloan_Deposit2_5instand6_Txn" time="1238.917" classname="tests.QCStore"/>
  <testcase name="JQC_TXMPDLDC_Newloan_Deposit2_5instand6_Txn" time="1205.721" classname="tests.QCStore"/>
  <testcase name="JQC_ILP_Newloan_Deposit_Return_Deposit_Txn" time="986.601" classname="tests.QCStore"/>
  <testcase name="JQC_ILP_Newloan_Deposit_Return_Deposit_Deposit_Txn" time="1041.377" classname="tests.QCStore"/>
  <testcase name="JQC_ILP_Newloan_ThreeDeposit_ThreeReturn_Default_NoCashOutRefinance_Txn" time="1264.904" classname="tests.QCStore">
    <error type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at tests.LegalGarnishment.lAndG(LegalGarnishment.java:193)
at tests.QCStore.JQC_ILP_Newloan_ThreeDeposit_ThreeReturn_Default_NoCashOutRefinance_Txn(QCStore.java:1248)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- JQC_ILP_Newloan_ThreeDeposit_ThreeReturn_Default_NoCashOutRefinance_Txn -->
  <testcase name="JQC_ILP_Newloan_ThreeDeposit_ThreeReturn_Default_YesCashOutRefinance_Txn" time="1351.242" classname="tests.QCStore">
    <error type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at tests.LegalGarnishment.lAndG(LegalGarnishment.java:193)
at tests.QCStore.JQC_ILP_Newloan_ThreeDeposit_ThreeReturn_Default_YesCashOutRefinance_Txn(QCStore.java:1378)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- JQC_ILP_Newloan_ThreeDeposit_ThreeReturn_Default_YesCashOutRefinance_Txn -->
</testsuite> <!-- tests.QCStore -->
